# Numpy

In [1]:
import numpy as np

In [2]:
np.array([10, 20, 24, 5, 15, 50])

array([10, 20, 24,  5, 15, 50])

In [3]:
a = np.array([10, 30, 20, 4, 30, 51, 7, 2, 4, 40, 100])
a[4]

30

In [4]:
a[3:]

array([  4,  30,  51,   7,   2,   4,  40, 100])

In [5]:
a[3:7]

array([ 4, 30, 51,  7])

In [6]:
a[1::4]

array([30, 51, 40])

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
ones = np.ones((4, 5))

In [9]:
type(ones)

numpy.ndarray

In [10]:
np.linspace(3, 10, 5)

array([ 3.  ,  4.75,  6.5 ,  8.25, 10.  ])

In [11]:
b = np.array([['x', 'y', 'z'], ['a', 'c', 'e']])
print(b)
type(b)

[['x' 'y' 'z']
 ['a' 'c' 'e']]


numpy.ndarray

In [12]:
b.ndim

2

In [13]:
c = [12, 4, 10, 12, 40]
np.sort(c)

array([ 4, 10, 12, 12, 40])

In [14]:
cabeceras = [('nombre', 'S10'), ('edad', int)]
datos = [('Juan', 10), ('Maria', 70), ('Javier', 42), ('Samuel', 15)]
usuarios = np.array(datos, dtype=cabeceras)

np.sort(usuarios, order='edad')

array([(b'Juan', 10), (b'Samuel', 15), (b'Javier', 42), (b'Maria', 70)],
      dtype=[('nombre', 'S10'), ('edad', '<i4')])

In [15]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [16]:
np.arange(5,30)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [17]:
np.arange(5, 50, 5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [18]:
np.full((3, 5), 10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [19]:
np.diag([0, 3, 9, 10])

array([[ 0,  0,  0,  0],
       [ 0,  3,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 10]])

# Pandas

In [20]:
import pandas as pd

In [22]:
series = pd.Series([5, 10, 15, 20, 25])
series

0     5
1    10
2    15
3    20
4    25
dtype: int64

In [23]:
type(series)

pandas.core.series.Series

In [24]:
series[3]

20

In [25]:
cad = pd.Series(['p', 'l', 'a', 't', 'z','i'])
cad

0    p
1    l
2    a
3    t
4    z
5    i
dtype: object

In [27]:
lst = ['Hola', 'mundo', 'robotico']
df = pd.DataFrame(lst)
print(df)

          0
0      Hola
1     mundo
2  robotico


In [30]:
data = {'Nombre': ['Juan','Ana', 'Jose', 'Arturo'],
       'Edad': [25, 18, 23, 27],
       'Pais': ['MX', 'CO', 'BR', 'MX']}

df = pd.DataFrame(data)
df

Nombre  Edad Pais
0    Juan    25   MX
1     Ana    18   CO
2    Jose    23   BR
3  Arturo    27   MX

In [32]:
print(df[['Nombre','Pais']])

   Nombre Pais
0    Juan   MX
1     Ana   CO
2    Jose   BR
3  Arturo   MX


In [34]:
data = pd.read_csv('canciones-2018.csv')
data.head(5)

id                          name       artists  \
0  6DCZcSspjsKoFjzjrWoCd                    God's Plan         Drake   
1  3ee8Jmje8o58CHK66QrVC                          SAD!  XXXTENTACION   
2  0e7ipj03S05BNilyu5bRz    rockstar (feat. 21 Savage)   Post Malone   
3  3swc6WTsr7rl9DqQKQA55  Psycho (feat. Ty Dolla $ign)   Post Malone   
4  2G7V7zsVDxg1yRsu7Ew9R                In My Feelings         Drake   

   danceability  energy  key  loudness  mode  speechiness  acousticness  \
0         0.754   0.449  7.0    -9.211   1.0       0.1090        0.0332   
1         0.740   0.613  8.0    -4.880   1.0       0.1450        0.2580   
2         0.587   0.535  5.0    -6.090   0.0       0.0898        0.1170   
3         0.739   0.559  8.0    -8.011   1.0       0.1170        0.5800   
4         0.835   0.626  1.0    -5.833   1.0       0.1250        0.0589   

   instrumentalness  liveness  valence    tempo  duration_ms  time_signature  
0          0.000083     0.552    0.357   77.169     198973.0             4.0  
1          0.003720     0.123    0.473   75.023     166606.0             4.0  
2          0.000066     0.131    0.140  159.847     218147.0             4.0  
3          0.000000     0.112    0.439  140.124     221440.0             4.0  
4          0.000060     0.396    0.350   91.030     217925.0             4.0

In [36]:
artista = data.artists
artista[5]

'Post Malone'

In [37]:
info = data.iloc[15]
info

id                     3GCdLUSnKSMJhs4Tj6CV3
name                All The Stars (with SZA)
artists                       Kendrick Lamar
danceability                           0.698
energy                                 0.633
key                                      8.0
loudness                              -4.946
mode                                     1.0
speechiness                           0.0597
acousticness                          0.0605
instrumentalness                    0.000194
liveness                              0.0926
valence                                0.552
tempo                                 96.924
duration_ms                         232187.0
time_signature                           4.0
Name: 15, dtype: object

In [38]:
data.tail()

id                               name       artists  \
95  630sXRhIcfwr2e4RdNtjK                  Rewrite The Stars     Zac Efron   
96  2xmrfQpmS2iJExTlklLoA  I Miss You (feat. Julia Michaels)  Clean Bandit   
97  5WvAo7DNuPRmk4APhdPzi                         No Brainer     DJ Khaled   
98  1j4kHkkpqZRBwE0A4CN4Y        Dusk Till Dawn - Radio Edit          ZAYN   
99  3EPXxR3ImUwfayaurPi3c                         Be Alright    Dean Lewis   

    danceability  energy   key  loudness  mode  speechiness  acousticness  \
95         0.684   0.619  10.0    -7.005   1.0       0.0386        0.0716   
96         0.638   0.658   3.0    -6.318   1.0       0.0456        0.2450   
97         0.552   0.760   0.0    -4.706   1.0       0.3420        0.0733   
98         0.258   0.437  11.0    -6.593   0.0       0.0390        0.1010   
99         0.553   0.586  11.0    -6.319   1.0       0.0362        0.6970   

    instrumentalness  liveness  valence    tempo  duration_ms  time_signature  
95          0.000000    0.1220   0.2840  125.046     217440.0             4.0  
96          0.000004    0.0919   0.3300  105.076     205748.0             4.0  
97          0.000000    0.0865   0.6390  135.702     260000.0             5.0  
98          0.000001    0.1060   0.0967  180.043     239000.0             4.0  
99          0.000000    0.0813   0.4430  126.684     196373.0             4.0

In [39]:
data.shape

(100, 16)

In [40]:
data.columns

Index(['id', 'name', 'artists', 'danceability', 'energy', 'key', 'loudness',
       'mode', 'speechiness', 'acousticness', 'instrumentalness', 'liveness',
       'valence', 'tempo', 'duration_ms', 'time_signature'],
      dtype='object')

In [41]:
data['tempo'].describe

<bound method NDFrame.describe of 0      77.169
1      75.023
2     159.847
3     140.124
4      91.030
       ...   
95    125.046
96    105.076
97    135.702
98    180.043
99    126.684
Name: tempo, Length: 100, dtype: float64>

In [42]:
data.sort_index(axis=0, ascending=False)

id                               name       artists  \
99  3EPXxR3ImUwfayaurPi3c                         Be Alright    Dean Lewis   
98  1j4kHkkpqZRBwE0A4CN4Y        Dusk Till Dawn - Radio Edit          ZAYN   
97  5WvAo7DNuPRmk4APhdPzi                         No Brainer     DJ Khaled   
96  2xmrfQpmS2iJExTlklLoA  I Miss You (feat. Julia Michaels)  Clean Bandit   
95  630sXRhIcfwr2e4RdNtjK                  Rewrite The Stars     Zac Efron   
..                    ...                                ...           ...   
4   2G7V7zsVDxg1yRsu7Ew9R                     In My Feelings         Drake   
3   3swc6WTsr7rl9DqQKQA55       Psycho (feat. Ty Dolla $ign)   Post Malone   
2   0e7ipj03S05BNilyu5bRz         rockstar (feat. 21 Savage)   Post Malone   
1   3ee8Jmje8o58CHK66QrVC                               SAD!  XXXTENTACION   
0   6DCZcSspjsKoFjzjrWoCd                         God's Plan         Drake   

    danceability  energy   key  loudness  mode  speechiness  acousticness  \
99         0.553   0.586  11.0    -6.319   1.0       0.0362        0.6970   
98         0.258   0.437  11.0    -6.593   0.0       0.0390        0.1010   
97         0.552   0.760   0.0    -4.706   1.0       0.3420        0.0733   
96         0.638   0.658   3.0    -6.318   1.0       0.0456        0.2450   
95         0.684   0.619  10.0    -7.005   1.0       0.0386        0.0716   
..           ...     ...   ...       ...   ...          ...           ...   
4          0.835   0.626   1.0    -5.833   1.0       0.1250        0.0589   
3          0.739   0.559   8.0    -8.011   1.0       0.1170        0.5800   
2          0.587   0.535   5.0    -6.090   0.0       0.0898        0.1170   
1          0.740   0.613   8.0    -4.880   1.0       0.1450        0.2580   
0          0.754   0.449   7.0    -9.211   1.0       0.1090        0.0332   

    instrumentalness  liveness  valence    tempo  duration_ms  time_signature  
99          0.000000    0.0813   0.4430  126.684     196373.0             4.0  
98          0.000001    0.1060   0.0967  180.043     239000.0             4.0  
97          0.000000    0.0865   0.6390  135.702     260000.0             5.0  
96          0.000004    0.0919   0.3300  105.076     205748.0             4.0  
95          0.000000    0.1220   0.2840  125.046     217440.0             4.0  
..               ...       ...      ...      ...          ...             ...  
4           0.000060    0.3960   0.3500   91.030     217925.0             4.0  
3           0.000000    0.1120   0.4390  140.124     221440.0             4.0  
2           0.000066    0.1310   0.1400  159.847     218147.0             4.0  
1           0.003720    0.1230   0.4730   75.023     166606.0             4.0  
0           0.000083    0.5520   0.3570   77.169     198973.0             4.0  

[100 rows x 16 columns]